url: "https://pedrogritter.github.io"
baseurl: ""
title: Pedro Gritter - Full Stack Developer
email: pedro12345g@gmail.com
description: Full Stack Developer specializing in modern web technologies
author: Pedro Gritter
social:
  name: Pedro Gritter
  links:
    - https://github.com/pedrogritter
    - https://linkedin.com/in/pedrogritter

# Build settings
# theme: minima
plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-sitemap

postcss:
  script: node_modules/.bin/postcss
  cache: false

# Performance Optimizations
sass:
  style: compressed
  sourcemap: never

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [html, head, body]
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
